### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by jing-yao** [leejaeyong7/patchmatch-rl#4]
When I was running 

> python bin/generate.py --experiment_name=EXPERIMENT_NAME0 --checkpoint_path=CHECKPOINT_PAT
H --dataset_path=TankandTemples --dataset=TanksAndTemples

there was a problem 

> Traceback (most recent call last):
  File "/home/ubuntu/space/patchmatch-rl-main/bin/generate.py", line 152, in <module>
    main(args)
  File "/home/ubuntu/space/patchmatch-rl-main/bin/generate.py", line 108, in main
    inf_p, inf_c = model(images, K, E, P, DIL, ranges, num_iterations=8, num_refine=2, num_views=NV, soft=False, details=False, train=False)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by jing-yao** [comment]
any answer？

**Comment by jing-yao** [comment]
I have solved this problem, but there is another problem.
I found that the size of all *****_conf_map.pth is about 1GB, is it normal？
